# Generated by Django 2.0.3 on 2018-03-22 00:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('helloworld', '0002_auto_20180322_1325'),
    ]

    operations = [
        migrations.AddField(
            model_name='document',
            name='views',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
    ]
